package com.example.diarybook.constant

object Constant{
    const val NOTE_DATA = "isNewNote"
    const val ARCHIVE_KEY = "isFromArchive"
    const val CALENDAR_KEY = "isFromCalendar"
    const val EMAIL_DATA = "keepEmail"
    const val WEB_CLIENT_ID = "129189507752-ek24rt2ph5tkgs6g9u4l1dc0e0f6uvo5.apps.googleusercontent.com"
    const val DIARY_AD_ID = "ca-app-pub-3940256099942544/1033173712"
    const val FULL_PHOTO_DATA = "fullPhoto"
    const val LANGUAGE_DATA = "languageData"
    const val CAMERA_PHOTO = "imageUri"
    const val FOLDER_PHOTO_CONTROL = "c"
    const val whiteHexCode = "#FFFFFFFF"
    const val blackHexCode = "#FF000000"
    const val SELECTED_CALENDAR_DATE_EN = "selectedCalendarViewDataEn"
    const val SELECTED_CALENDAR_DATE_TR = "selectedCalendarViewDateTr"
    const val languageCodeTr = "tr"
    const val languageCodeEn = "en"
    const val BACKGROUND_DATA = "fromBackgroundOptions"
    const val monthFormat = "MMMM"
    const val dateFormat = "dd MMMM EEEE"
    const val githubAccount = "https://github.com/mustafakamber"
    const val gmailAccount = "mustkmber@gmail.com"
    const val FILE_PROVIDER_PACKAGE = "com.example.diarybook.fileprovider"
    const val notificationId = 1
    const val nullEmail = ""
    const val channelID = "channel1"
    const val notificationTitle = "titleExtra"
    const val notificationMessage = "messageExtra"
    const val notificationChannelName = "Notification Channel"
    const val notificationDescription = "A Description of the Channel"
    const val baseUrl = "https://raw.githubusercontent.com/"
    const val extUrl = "mustafakamber/CalendarImageDataJSON/main/calendarList.json"
}